"use client";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Providers from './Providers.tsx';
import {Header} from './Header.tsx';

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

//export const metadata: Metadata = {
 // title: "Create Next App",
 // description: "Generated by create next app",
//};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
	
	
  return (
    <html lang="en">
      <Providers>
	  <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
		<Header/>

        {children}
		
	  </body>
	  </Providers>
    </html>
  );
}
